# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.tresp_Rcpp <- function(tmat, tmin, tmax, topt) {
    .Call(`_infect_tresp_Rcpp`, tmat, tmin, tmax, topt)
}

